name: Bike Walk Vote
markdown: redcarpet
highlighter: true
author: Bike Walk Vote Political Action Committee
facebook_app: 441294915999028
google_analytics: UA-27483955-1
collections:
  endorsements:
    output: true
defaults:
  - scope:
      path: ""
      type: endorsements
    values:
      layout: endorsement
